### PR TITLE
Patchday

### LINKED ISSUE #21: Dipoles for synthetic arrays
We would like to be able to provide some kind of more physically correct dipole pattern for the synthetic arrays. the only place where we need to figure this out is in arrays.generateUniformArbitrary

### PR DESCRIPTION
**Pull request by MichaelDoebereiner**
Extension of array generators for arbitrary sizes and frequencies based on dipole or patch elements.

See: demo/arrayGeneration.py

Closes #21

### CODE REVIEW

**Comment by SebastianSemper** [comment]
Since we now have the possibility to generate synthetic wideband arrays, we need to be able to pass the "keepNarrowBand" kwarg down to the constructor of the returned eadf objects.

**Comment by SebastianSemper** [comment]
test_keyError and test_value in the matlabimporters tests do fail. they should not.

**Comment by SebastianSemper** [comment]
Otherwise everything seems to work fine. After the last few tests run, we can merge. Nice!

**Comment by SebastianSemper** [comment]
Just a note: I ran the tests for the first time on the GPU. They run through flawlessly. We are so lucky. :D

**Comment by MichaelDoebereiner** [comment]
> 
> 
> Otherwise everything seems to work fine. After the last few tests run, we can merge. Nice!

Fixed those tests and we're ready to go!

**Comment by SebastianSemper** [comment]
Nice. Merged.

**Pull request merged**
